#!/usr/bin/env python3
"""CDK app: replaces main.py + the manual AWS console clicks.

Stack layout (a linear dependency chain, no cycles):

    DataStack      DynamoDB table + GSI
        |
    IngestStack    S3 bucket + size-tracking lambda + S3 -> lambda trigger
        |
    PlotApiStack   matplotlib layer + plotting lambda + REST API (/plot GET)
        |
    DriverStack    driver lambda (knows the API URL + the bucket)

No resource names are hardcoded: bucket / table / function / API names are all
auto-generated by CloudFormation, and the generated values are handed to the
lambdas through environment variables.
"""

import os

from aws_cdk import App, Environment
from stacks.data_stack import DataStack
from stacks.driver_stack import DriverStack
from stacks.ingest_stack import IngestStack
from stacks.plot_api_stack import PlotApiStack

app = App()

# Environment-specific synthesis so the auto-named, globally-unique S3 bucket
# resolves against the real account/region instead of an env-agnostic token.
env = Environment(
    account=os.environ.get("CDK_DEFAULT_ACCOUNT"),
    region=os.environ.get("CDK_DEFAULT_REGION", "us-east-1"),
)

data = DataStack(app, "DataStack", env=env)

ingest = IngestStack(
    app,
    "IngestStack",
    table=data.table,
    gsi_partition_value=DataStack.GSI_PARTITION_VALUE,
    env=env,
)

plot_api = PlotApiStack(
    app,
    "PlotApiStack",
    table=data.table,
    gsi_name=DataStack.GSI_NAME,
    gsi_partition_value=DataStack.GSI_PARTITION_VALUE,
    bucket=ingest.bucket,
    env=env,
)

DriverStack(
    app,
    "DriverStack",
    bucket=ingest.bucket,
    plot_api=plot_api.api,
    env=env,
)

app.synth()
